package repl.classloader;

import java.io.IOException;
import java.net.URL;
import java.util.Collections;
import java.util.Enumeration;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Makes classes and resources from an isolated application classloader visible
 * to code generated by the embedded Clojure compiler while retaining the
 * agent/Clojure classloader as a fallback.
 */
public final class BridgeClassLoader extends ClassLoader {
    private final ClassLoader target;

    public BridgeClassLoader(ClassLoader target, ClassLoader fallback) {
        super(fallback);
        if (target == null) {
            throw new IllegalArgumentException("target classloader is required");
        }
        this.target = target;
    }

    private static boolean isAgentRuntimeClass(String name) {
        return name.startsWith("clojure.")
                || name.startsWith("nrepl.")
                || name.startsWith("cider.")
                || name.startsWith("repl.");
    }

    private static boolean isAgentRuntimeResource(String name) {
        return name.startsWith("clojure/")
                || name.startsWith("nrepl/")
                || name.startsWith("cider/")
                || name.startsWith("repl/");
    }

    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        synchronized (getClassLoadingLock(name)) {
            Class<?> loaded = findLoadedClass(name);
            if (loaded == null) {
                if (isAgentRuntimeClass(name)) {
                    try {
                        loaded = super.loadClass(name, false);
                    } catch (ClassNotFoundException ignored) {
                        loaded = target.loadClass(name);
                    }
                } else {
                    try {
                        loaded = target.loadClass(name);
                    } catch (ClassNotFoundException ignored) {
                        loaded = super.loadClass(name, false);
                    }
                }
            }
            if (resolve && loaded.getClassLoader() == this) {
                resolveClass(loaded);
            }
            return loaded;
        }
    }

    @Override
    public URL getResource(String name) {
        URL resource = isAgentRuntimeResource(name) ? super.getResource(name) : target.getResource(name);
        if (resource != null) {
            return resource;
        }
        return isAgentRuntimeResource(name) ? target.getResource(name) : super.getResource(name);
    }

    @Override
    public Enumeration<URL> getResources(String name) throws IOException {
        Set<URL> resources = new LinkedHashSet<>();
        if (isAgentRuntimeResource(name)) {
            resources.addAll(Collections.list(super.getResources(name)));
            resources.addAll(Collections.list(target.getResources(name)));
        } else {
            resources.addAll(Collections.list(target.getResources(name)));
            resources.addAll(Collections.list(super.getResources(name)));
        }
        return Collections.enumeration(resources);
    }
}
